swagger: '2.0'
info:
  title: Academic Disciplines
  description: Web API to get academic disciplines, including majors, minors, and concentrations.
  version: "1"
  license:
    name: GNU Affero General Public License Version 3
    url: http://www.gnu.org/licenses/agpl-3.0.en.html
externalDocs:
  description: GitHub Repository
  url: https://github.com/osu-mist/academic-disciplines-api
schemes:
  - https
basePath: /v1/catalog
produces:
  - application/json
paths:
  /academic-disciplines:
    get:
      tags:
      - disciplines
      operationId: getDisciplines
      description: "Get a list of majors, minors, and concentrations. Filter by query parameters."
      parameters:
        - name: major
          in: query
          description: >
            If true, disciplines that can be majors will be included.
            If false, disciplines that can be majors will be excluded.
          type: boolean
          required: false
        - name: minor
          in: query
          description: >
            If true, disciplines that can be minors will be included.
            If false, disciplines that can be minors will be excluded.
          type: boolean
          required: false
        - name: concentration
          in: query
          description: >
            If true, disciplines that can be concentrations will be included.
            If false, disciplines that can be concentrations will be excluded.
          type: boolean
          required: false
        - name: department
          in: query
          description: Filter by department code.
          type: string
          required: false
        - $ref: '#/parameters/pretty'
      responses:
        "200":
          description: Successful response
          schema:
            $ref: "#/definitions/DisciplineResultObject"
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/Error"
  /academic-disciplines/{id}:
    get:
      tags:
      - disciplines
      operationId: getDisciplineByID
      description: "Get a concentration by code/ID"
      parameters:
        - name: id
          in: path
          description: "ID/code of discipline to retrieve."
          type: string
          required: true
        - $ref: '#/parameters/pretty'
      responses:
        "200":
          description: Successful response
          schema:
            $ref: "#/definitions/DisciplineResultObject"
        "404":
          description: Not found
          schema:
            $ref: "#/definitions/Error"
parameters:
  pretty:
    name: pretty
    in: query
    type: boolean
    required: false
    description: If true, JSON response will be pretty-printed
definitions:
  DisciplineResultObject:
    properties:
      links:
        $ref: "#/definitions/ResourceLinks"
      data:
        type: array
        items:
          $ref: "#/definitions/Presentation"
  Presentation:
    properties:
      id:
        type: string
        description: Discipline code
      type:
        type: string
      attributes:
        $ref: "#/definitions/DisciplineAttributes"
      links:
        $ref: "#/definitions/ResourceLinks"
  DisciplineAttributes:
    properties:
      description:
        type: string
        description: Description of discipline.
      descriptionLong:
        type: string
        description: Long description of discipline.
      validMajor:
        type: boolean
      validMinor:
        type: boolean
      validConcentration:
        type: boolean
      department:
        type: string
        description: Department code
      cipcCode:
        type: string
  ResourceLinks:
    properties:
      self:
        type: string
  Error:
    type: object
    properties:
      status:
        type: integer
        format: int32
        description: HTTP status code.
      developerMessage:
        type: string
        description: An error string aimed at developers.
      userMessage:
        type: string
        description: An error string aimed at end users.
      code:
        type: integer
        description: Error code.
      details:
        type: string
        description: A link to further information about the error.
