swagger: '2.0'
info:
  title: Academic Disciplines
  description: Web API to get academic disciplines, including majors, minors, and concentrations.
  version: "1"
  license:
    name: GNU Affero General Public License Version 3
    url: http://www.gnu.org/licenses/agpl-3.0.en.html
externalDocs:
  description: GitHub Repository
  url: https://github.com/osu-mist/academic-disciplines-api
schemes:
  - https
basePath: /v1/catalog
produces:
  - application/json
paths:
  /academic-disciplines:
    get:
      tags:
      - disciplines
      operationId: getDisciplines
      description: "Get a list of majors, minors, and concentrations. Filter by query parameters."
      parameters:
        - name: type
          in: query
          description: "Filter by discipline type. Valid types are major, minor, or concentration."
          type: string
          required: false
          collectionFormat: multi
        - $ref: '#/parameters/pretty'
      responses:
        "200":
          description: Successful response
          schema:
            $ref: "#/definitions/DisciplineResultObject"
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/Error"
  /academic-disciplines/{id}:
    get:
      tags:
      - disciplines
      operationId: getDisciplineByID
      description: "Get a list of majors, minors, and concentrations. Filter by query parameters."
      parameters:
        - name: id
          in: path
          description: "ID of discipline to retrieve."
          type: string
          required: true
        - $ref: '#/parameters/pretty'
      responses:
        "200":
          description: Successful response
          schema:
            $ref: "#/definitions/DisciplineResultObject"
        "404":
          description: Not found
          schema:
            $ref: "#/definitions/Error"
parameters:
  pretty:
    name: pretty
    in: query
    type: boolean
    required: false
    description: If true, JSON response will be pretty-printed
definitions:
  DisciplineResultObject:
    properties:
      links:
        $ref: "#/definitions/ResourceLinks"
      data:
        type: array
        items:
          $ref: "#/definitions/Presentation"
  Presentation:
    properties:
      id:
        type: string
      type:
        type: string
      attributes:
        $ref: "#/definitions/DisciplineAttributes"
      links:
        $ref: "#/definitions/ResourceLinks"
  DisciplineAttributes:
    properties:
      title:
        type: string
        format: Title of discipline.
      type:
        type: string
        format: "major, minor, or concentration"
      abbreviation:
        type: string
  ResourceLinks:
    properties:
      self:
        type: string
  Error:
    type: object
    properties:
      status:
        type: integer
        format: int32
        description: HTTP status code.
      developerMessage:
        type: string
        description: An error string aimed at developers.
      userMessage:
        type: string
        description: An error string aimed at end users.
      code:
        type: integer
        description: Error code.
      details:
        type: string
        description: A link to further information about the error.
